### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by sauron65** [Digital-Electronics-LLC/digitalElectronicsLLC-website#2]
how does this repository get deployed to https://digital-electronics.w3spaces.com/ ?

**Comment by ghost** [comment]
@DiamondCoder1000 deploys it.

**Comment by sauron65** [comment]
why isn't github pages used for this?

**Comment by backfromhiatus** [comment]
Because, Idk how use it

**Comment by backfromhiatus** [comment]
Also, github pages kids sucks
